# Generated by Django 4.1.7 on 2023-02-27 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.role'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='UserRole',
        ),
    ]
